<h1><b>Week 3 Assignment: Segmenting and Clustering Neighborhoods in Toronto</b></h1>

<h2>Contents</h2>
<h3>Task 1: Use pandas, or the BeautifulSoup package, or any other way you are comfortable with to transform the data in the table on the Wikipedia page into the above pandas dataframe.</h3>
<h3>Task 2: Use the Geocoder package or the csv file to create the following dataframe</h3>
<h3>Task 3: Explore and cluster the neighborhoods in Toronto</h3>

<h1><b>Task 1:</b> Use pandas, or the BeautifulSoup package, or any other way you are comfortable with to transform the data in the table on the Wikipedia page into the above pandas dataframe.</h1>

In [94]:
!pip3 install bs4
!pip3 install requests
!pip3 install pandas

Requirement already satisfied: bs4 in /usr/local/lib/python3.8/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/site-packages (from bs4) (4.9.3)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in /usr/local/lib/python3.8/site-packages (from beautifulsoup4->bs4) (2.2.1)
Requirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests) (1.25.10)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/site-packages (1.3.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/rolandrosshadi/Library/Python/3.8/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/site-packages (from pandas) (1.19.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [95]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

<h3>Initialise variables</h3>

In [96]:
target_url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
data = requests.get(target_url).text
soup = BeautifulSoup(data, 'html.parser')

<h3>Scrape data from wikipedia page to pandas dataframe</h3>

In [97]:
table_contents = []
table = soup.find('table')
for row in table.findAll('td'):
    cell = {}
    if row.span.text == 'Not assigned':
        pass
    else:
        cell['PostalCode'] = row.p.text[:3]
        cell['Borough'] = (row.span.text).split('(')[0]
        cell['Neighborhood'] = (((((row.span.text).split('(')[1]).strip(')')).replace(
            ' /', ',')).replace(')', ' ')).strip(' ')
        table_contents.append(cell)

df = pd.DataFrame(table_contents)
df['Borough'] = df['Borough'].replace({'Downtown TorontoStn A PO Boxes25 The Esplanade': 'Downtown Toronto Stn A',
                                      'East TorontoBusiness reply mail Processing Centre969 Eastern': 'East Toronto Business',
                                       'EtobicokeNorthwest': 'Etobicoke Northwest', 'East YorkEast Toronto': 'East York/East Toronto',
                                       'MississaugaCanada Post Gateway Processing Centre': 'Mississauga'})

#sort by PostalCode asc
df.sort_values(by=['PostalCode'])

,PostalCode,Borough,Neighborhood
6,M1B,Scarborough,"Malvern, Rouge"
12,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
18,M1E,Scarborough,"Guildwood, Morningside, West Hill"
22,M1G,Scarborough,Woburn
26,M1H,Scarborough,Cedarbrae
32,M1J,Scarborough,Scarborough Village
38,M1K,Scarborough,"Kennedy Park, Ionview, East Birchmount Park"
44,M1L,Scarborough,"Golden Mile, Clairlea, Oakridge"
51,M1M,Scarborough,"Cliffside, Cliffcrest, Scarborough Village West"
58,M1N,Scarborough,"Birch Cliff, Cliffside West"
65,M1P,Scarborough,"Dorset Park, Wexford Heights, Scarborough Town..."
71,M1R,Scarborough,"Wexford, Maryvale"
78,M1S,Scarborough,Agincourt
82,M1T,Scarborough,"Clarks Corners, Tam O'Shanter, Sullivan"
85,M1V,Scarborough,"Milliken, Agincourt North, Steeles East, L'Amo..."
90,M1W,Scarborough,"Steeles West, L'Amoreaux West"
95,M1X,Scarborough,Upper Rouge
27,M2H,North York,Hillcrest Village
33,M2J,North York,"Fairview, Henry Farm, Oriole"
39,M2K,North York,Bayview Village
45,M2L,North York,"York Mills, Silver Hills"
52,M2M,North York,"Willowdale, Newtonbrook"
59,M2N,North York,Willowdale South
66,M2P,North York,York Mills West
72,M2R,North York,Willowdale West
0,M3A,North York,Parkwoods
7,M3B,North York,Don Mills North
13,M3C,North York,Don Mills South
28,M3H,North York,"Bathurst Manor, Wilson Heights, Downsview North"
34,M3J,North York,"Northwood Park, York University"
40,M3K,North York,Downsview East
46,M3L,North York,Downsview West
53,M3M,North York,Downsview Central
60,M3N,North York,Downsview Northwest
1,M4A,North York,Victoria Village
8,M4B,East York,"Parkview Hill, Woodbine Gardens"
14,M4C,East York,Woodbine Heights
19,M4E,East Toronto,The Beaches
23,M4G,East York,Leaside
29,M4H,East York,Thorncliffe Park
35,M4J,East York/East Toronto,The Danforth East
41,M4K,East Toronto,"The Danforth West, Riverdale"
47,M4L,East Toronto,"India Bazaar, The Beaches West"
54,M4M,East Toronto,Studio District
61,M4N,Central Toronto,Lawrence Park
67,M4P,Central Toronto,Davisville North
73,M4R,Central Toronto,North Toronto West
79,M4S,Central Toronto,Davisville
83,M4T,Central Toronto,"Moore Park, Summerhill East"
86,M4V,Central Toronto,"Summerhill West, Rathnelly, South Hill, Forest..."
91,M4W,Downtown Toronto,Rosedale
96,M4X,Downtown Toronto,"St. James Town, Cabbagetown"
99,M4Y,Downtown Toronto,Church and Wellesley
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
9,M5B,Downtown Toronto,"Garden District, Ryerson"
15,M5C,Downtown Toronto,St. James Town
20,M5E,Downtown Toronto,Berczy Park
24,M5G,Downtown Toronto,Central Bay Street
30,M5H,Downtown Toronto,"Richmond, Adelaide, King"
36,M5J,Downtown Toronto,"Harbourfront East, Union Station, Toronto Islands"
42,M5K,Downtown Toronto,"Toronto Dominion Centre, Design Exchange"
48,M5L,Downtown Toronto,"Commerce Court, Victoria Hotel"
55,M5M,North York,"Bedford Park, Lawrence Manor East"
62,M5N,Central Toronto,Roselawn
68,M5P,Central Toronto,Forest Hill North & West
74,M5R,Central Toronto,"The Annex, North Midtown, Yorkville"
80,M5S,Downtown Toronto,"University of Toronto, Harbord"
84,M5T,Downtown Toronto,"Kensington Market, Chinatown, Grange Park"
87,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har..."
92,M5W,Downtown Toronto Stn A,Enclave of M5E
97,M5X,Downtown Toronto,"First Canadian Place, Underground city"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
10,M6B,North York,Glencairn
16,M6C,York,Humewood-Cedarvale
21,M6E,York,Caledonia-Fairbanks
25,M6G,Downtown Toronto,Christie
31,M6H,West Toronto,"Dufferin, Dovercourt Village"
37,M6J,West Toronto,"Little Portugal, Trinity"
43,M6K,West Toronto,"Brockton, Parkdale Village, Exhibition Place"
49,M6L,North York,"North Park, Maple Leaf Park, Upwood Park"
56,M6M,York,"Del Ray, Mount Dennis, Keelsdale and Silverthorn"
63,M6N,York,"Runnymede, The Junction North"
69,M6P,West Toronto,"High Park, The Junction South"
75,M6R,West Toronto,"Parkdale, Roncesvalles"
81,M6S,West Toronto,"Runnymede, Swansea"
4,M7A,Queen's Park,Ontario Provincial Government
76,M7R,Mississauga,Enclave of L4W
100,M7Y,East Toronto Business,Enclave of M4L
88,M8V,Etobicoke,"New Toronto, Mimico South, Humber Bay Shores"
93,M8W,Etobicoke,"Alderwood, Long Branch"
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
5,M9A,Etobicoke,Islington Avenue
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
17,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe..."
50,M9L,North York,Humber Summit
57,M9M,North York,"Humberlea, Emery"
64,M9N,York,Weston
70,M9P,Etobicoke,Westmount
77,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
89,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
94,M9W,Etobicoke Northwest,"Clairville, Humberwood, Woodbine Downs, West H..."

<h3>Dataframe Shape</h3>

In [98]:
df.shape

(103, 3)

In [99]:
print('The dataframe has {} boroughs and {} neighborhoods.'.format(
    len(df['Borough'].unique()),
    df.shape[0]))

The dataframe has 15 boroughs and 103 neighborhoods.

<h1><b>Task 2:</b> Use the Geocoder package or the csv file to create the following dataframe</h1>

<h3>Get Latitude & Longitude data using Geospatial_Coordinates.csv</h3>

In [100]:
df_LL = pd.read_csv(
    r'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/labs_v1/Geospatial_Coordinates.csv')
print(df_LL)

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
5           M1J  43.744734 -79.239476
6           M1K  43.727929 -79.262029
7           M1L  43.711112 -79.284577
8           M1M  43.716316 -79.239476
9           M1N  43.692657 -79.264848
10          M1P  43.757410 -79.273304
11          M1R  43.750071 -79.295849
12          M1S  43.794200 -79.262029
13          M1T  43.781638 -79.304302
14          M1V  43.815252 -79.284577
15          M1W  43.799525 -79.318389
16          M1X  43.836125 -79.205636
17          M2H  43.803762 -79.363452
18          M2J  43.778517 -79.346556
19          M2K  43.786947 -79.385975
20          M2L  43.757490 -79.374714
21          M2M  43.789053 -79.408493
22          M2N  43.770120 -79.408493
23          M2P  43.752758 -79.400049
24          M2R  43.782736 -79.442259
25          M3A  43.753259 -79.329656
26          M3B  43.745906 -79.352188
27          M3C  43.725900 -79.340923
28          M3H  43.754328 -79.442259
29          M3J  43.767980 -79.487262
30          M3K  43.737473 -79.464763
31          M3L  43.739015 -79.506944
32          M3M  43.728496 -79.495697
33          M3N  43.761631 -79.520999
34          M4A  43.725882 -79.315572
35          M4B  43.706397 -79.309937
36          M4C  43.695344 -79.318389
37          M4E  43.676357 -79.293031
38          M4G  43.709060 -79.363452
39          M4H  43.705369 -79.349372
40          M4J  43.685347 -79.338106
41          M4K  43.679557 -79.352188
42          M4L  43.668999 -79.315572
43          M4M  43.659526 -79.340923
44          M4N  43.728020 -79.388790
45          M4P  43.712751 -79.390197
46          M4R  43.715383 -79.405678
47          M4S  43.704324 -79.388790
48          M4T  43.689574 -79.383160
49          M4V  43.686412 -79.400049
50          M4W  43.679563 -79.377529
51          M4X  43.667967 -79.367675
52          M4Y  43.665860 -79.383160
53          M5A  43.654260 -79.360636
54          M5B  43.657162 -79.378937
55          M5C  43.651494 -79.375418
56          M5E  43.644771 -79.373306
57          M5G  43.657952 -79.387383
58          M5H  43.650571 -79.384568
59          M5J  43.640816 -79.381752
60          M5K  43.647177 -79.381576
61          M5L  43.648198 -79.379817
62          M5M  43.733283 -79.419750
63          M5N  43.711695 -79.416936
64          M5P  43.696948 -79.411307
65          M5R  43.672710 -79.405678
66          M5S  43.662696 -79.400049
67          M5T  43.653206 -79.400049
68          M5V  43.628947 -79.394420
69          M5W  43.646435 -79.374846
70          M5X  43.648429 -79.382280
71          M6A  43.718518 -79.464763
72          M6B  43.709577 -79.445073
73          M6C  43.693781 -79.428191
74          M6E  43.689026 -79.453512
75          M6G  43.669542 -79.422564
76          M6H  43.669005 -79.442259
77          M6J  43.647927 -79.419750
78          M6K  43.636847 -79.428191
79          M6L  43.713756 -79.490074
80          M6M  43.691116 -79.476013
81          M6N  43.673185 -79.487262
82          M6P  43.661608 -79.464763
83          M6R  43.648960 -79.456325
84          M6S  43.651571 -79.484450
85          M7A  43.662301 -79.389494
86          M7R  43.636966 -79.615819
87          M7Y  43.662744 -79.321558
88          M8V  43.605647 -79.501321
89          M8W  43.602414 -79.543484
90          M8X  43.653654 -79.506944
91          M8Y  43.636258 -79.498509
92          M8Z  43.628841 -79.520999
93          M9A  43.667856 -79.532242
94          M9B  43.650943 -79.554724
95          M9C  43.643515 -79.577201
96          M9L  43.756303 -79.565963
97          M9M  43.724766 -79.532242
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

<h3>Rename Postal Code Column and Merge PostalCode</h3>

In [101]:
df_LL.rename(columns={'Postal Code': 'PostalCode'}, inplace=True)
neighborhoods = pd.merge(df, df_LL, on='PostalCode', how='inner')
neighborhoods

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Queen's Park,Ontario Provincial Government,43.662301,-79.389494
5,M9A,Etobicoke,Islington Avenue,43.667856,-79.532242
6,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills North,43.745906,-79.352188
8,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937
10,M6B,North York,Glencairn,43.709577,-79.445073
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov...",43.650943,-79.554724
12,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
13,M3C,North York,Don Mills South,43.725900,-79.340923
14,M4C,East York,Woodbine Heights,43.695344,-79.318389
15,M5C,Downtown Toronto,St. James Town,43.651494,-79.375418
16,M6C,York,Humewood-Cedarvale,43.693781,-79.428191
17,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe...",43.643515,-79.577201
18,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
19,M4E,East Toronto,The Beaches,43.676357,-79.293031
20,M5E,Downtown Toronto,Berczy Park,43.644771,-79.373306
21,M6E,York,Caledonia-Fairbanks,43.689026,-79.453512
22,M1G,Scarborough,Woburn,43.770992,-79.216917
23,M4G,East York,Leaside,43.709060,-79.363452
24,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
25,M6G,Downtown Toronto,Christie,43.669542,-79.422564
26,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
27,M2H,North York,Hillcrest Village,43.803762,-79.363452
28,M3H,North York,"Bathurst Manor, Wilson Heights, Downsview North",43.754328,-79.442259
29,M4H,East York,Thorncliffe Park,43.705369,-79.349372
30,M5H,Downtown Toronto,"Richmond, Adelaide, King",43.650571,-79.384568
31,M6H,West Toronto,"Dufferin, Dovercourt Village",43.669005,-79.442259
32,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
33,M2J,North York,"Fairview, Henry Farm, Oriole",43.778517,-79.346556
34,M3J,North York,"Northwood Park, York University",43.767980,-79.487262
35,M4J,East York/East Toronto,The Danforth East,43.685347,-79.338106
36,M5J,Downtown Toronto,"Harbourfront East, Union Station, Toronto Islands",43.640816,-79.381752
37,M6J,West Toronto,"Little Portugal, Trinity",43.647927,-79.419750
38,M1K,Scarborough,"Kennedy Park, Ionview, East Birchmount Park",43.727929,-79.262029
39,M2K,North York,Bayview Village,43.786947,-79.385975
40,M3K,North York,Downsview East,43.737473,-79.464763
41,M4K,East Toronto,"The Danforth West, Riverdale",43.679557,-79.352188
42,M5K,Downtown Toronto,"Toronto Dominion Centre, Design Exchange",43.647177,-79.381576
43,M6K,West Toronto,"Brockton, Parkdale Village, Exhibition Place",43.636847,-79.428191
44,M1L,Scarborough,"Golden Mile, Clairlea, Oakridge",43.711112,-79.284577
45,M2L,North York,"York Mills, Silver Hills",43.757490,-79.374714
46,M3L,North York,Downsview West,43.739015,-79.506944
47,M4L,East Toronto,"India Bazaar, The Beaches West",43.668999,-79.315572
48,M5L,Downtown Toronto,"Commerce Court, Victoria Hotel",43.648198,-79.379817
49,M6L,North York,"North Park, Maple Leaf Park, Upwood Park",43.713756,-79.490074
50,M9L,North York,Humber Summit,43.756303,-79.565963
51,M1M,Scarborough,"Cliffside, Cliffcrest, Scarborough Village West",43.716316,-79.239476
52,M2M,North York,"Willowdale, Newtonbrook",43.789053,-79.408493
53,M3M,North York,Downsview Central,43.728496,-79.495697
54,M4M,East Toronto,Studio District,43.659526,-79.340923
55,M5M,North York,"Bedford Park, Lawrence Manor East",43.733283,-79.419750
56,M6M,York,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013
57,M9M,North York,"Humberlea, Emery",43.724766,-79.532242
58,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848
59,M2N,North York,Willowdale South,43.770120,-79.408493
60,M3N,North York,Downsview Northwest,43.761631,-79.520999
61,M4N,Central Toronto,Lawrence Park,43.728020,-79.388790
62,M5N,Central Toronto,Roselawn,43.711695,-79.416936
63,M6N,York,"Runnymede, The Junction North",43.673185,-79.487262
64,M9N,York,Weston,43.706876,-79.518188
65,M1P,Scarborough,"Dorset Park, Wexford Heights, Scarborough Town...",43.757410,-79.273304
66,M2P,North York,York Mills West,43.752758,-79.400049
67,M4P,Central Toronto,Davisville North,43.712751,-79.390197
68,M5P,Central Toronto,Forest Hill North & West,43.696948,-79.411307
69,M6P,West Toronto,"High Park, The Junction South",43.661608,-79.464763
70,M9P,Etobicoke,Westmount,43.696319,-79.532242
71,M1R,Scarborough,"Wexford, Maryvale",43.750071,-79.295849
72,M2R,North York,Willowdale West,43.782736,-79.442259
73,M4R,Central Toronto,North Toronto West,43.715383,-79.405678
74,M5R,Central Toronto,"The Annex, North Midtown, Yorkville",43.672710,-79.405678
75,M6R,West Toronto,"Parkdale, Roncesvalles",43.648960,-79.456325
76,M7R,Mississauga,Enclave of L4W,43.636966,-79.615819
77,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
78,M1S,Scarborough,Agincourt,43.794200,-79.262029
79,M4S,Central Toronto,Davisville,43.704324,-79.388790
80,M5S,Downtown Toronto,"University of Toronto, Harbord",43.662696,-79.400049
81,M6S,West Toronto,"Runnymede, Swansea",43.651571,-79.484450
82,M1T,Scarborough,"Clarks Corners, Tam O'Shanter, Sullivan",43.781638,-79.304302
83,M4T,Central Toronto,"Moore Park, Summerhill East",43.689574,-79.383160
84,M5T,Downtown Toronto,"Kensington Market, Chinatown, Grange Park",43.653206,-79.400049
85,M1V,Scarborough,"Milliken, Agincourt North, Steeles East, L'Amo...",43.815252,-79.284577
86,M4V,Central Toronto,"Summerhill West, Rathnelly, South Hill, Forest...",43.686412,-79.400049
87,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har...",43.628947,-79.394420
88,M8V,Etobicoke,"New Toronto, Mimico South, Humber Bay Shores",43.605647,-79.501321
89,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
90,M1W,Scarborough,"Steeles West, L'Amoreaux West",43.799525,-79.318389
91,M4W,Downtown Toronto,Rosedale,43.679563,-79.377529
92,M5W,Downtown Toronto Stn A,Enclave of M5E,43.646435,-79.374846
93,M8W,Etobicoke,"Alderwood, Long Branch",43.602414,-79.543484
94,M9W,Etobicoke Northwest,"Clairville, Humberwood, Woodbine Downs, West H...",43.706748,-79.594054
95,M1X,Scarborough,Upper Rouge,43.836125,-79.205636
96,M4X,Downtown Toronto,"St. James Town, Cabbagetown",43.667967,-79.367675
97,M5X,Downtown Toronto,"First Canadian Place, Underground city",43.648429,-79.382280
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto Business,Enclave of M4L,43.662744,-79.321558
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999

<h1><b>Task 3:</b> Explore and cluster the neighborhoods in Toronto</h1>

In [102]:
!pip3 install geopy
!pip3 install folium
!pip3 install sklearn
!pip3 install matplotlib

Requirement already satisfied: geopy in /usr/local/lib/python3.8/site-packages (2.2.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /usr/local/lib/python3.8/site-packages (from geopy) (1.52)
Requirement already satisfied: folium in /usr/local/lib/python3.8/site-packages (0.12.1)
Requirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (from folium) (2.24.0)
Requirement already satisfied: branca>=0.3.0 in /usr/local/lib/python3.8/site-packages (from folium) (0.4.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/site-packages (from folium) (1.19.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.8/site-packages (from folium) (3.0.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests->folium) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests->folium) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests->folium) (2020.6.20)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/site-packages (from jinja2>=2.9->folium) (2.0.1)
Requirement already satisfied: sklearn in /usr/local/lib/python3.8/site-packages (0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.8/site-packages (from sklearn) (0.24.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/site-packages (from scikit-learn->sklearn) (2.2.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.19.2)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.5.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/site-packages (from scikit-learn->sklearn) (0.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/site-packages (3.4.2)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.8/site-packages (from matplotlib) (1.19.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/rolandrosshadi/Library/Python/3.8/lib/python/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.8/site-packages (from matplotlib) (8.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib) (1.15.0)

In [103]:
import folium
from sklearn.cluster import KMeans
import matplotlib.colors as colors
import matplotlib.cm as cm
from pandas.io.json import json_normalize
import requests
from geopy.geocoders import Nominatim
import json
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
print('Libraries imported.')

Libraries imported.

<h3>Identify Longitude & Latitude of Toronto</h3>

In [104]:
address = 'Toronto, Ontario'
geolocator = Nominatim(user_agent="toronto_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Toronto are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Toronto are 43.6534817, -79.3839347.

<h3>Map of Toronto with Neighborhoods superimposed</h3>

In [105]:
map_toronto = folium.Map(location=[latitude, longitude], zoom_start=10)

for lat, lng, borough, neighborhood in zip(neighborhoods['Latitude'], neighborhoods['Longitude'], neighborhoods['Borough'], neighborhoods['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_toronto)  
    
map_toronto

<h3>Identify the Borough with the most postcodes</h3>

In [106]:
neighborhoods['Borough'].value_counts()

North York                24
Downtown Toronto          17
Scarborough               17
Etobicoke                 11
Central Toronto            9
West Toronto               6
York                       5
East York                  4
East Toronto               4
Queen's Park               1
East York/East Toronto     1
Mississauga                1
Downtown Toronto Stn A     1
Etobicoke Northwest        1
East Toronto Business      1
Name: Borough, dtype: int64

<h3>North York chosen for Analysis. Co-ordinates for North York:</h3>

In [107]:
northyork_data = neighborhoods[neighborhoods['Borough']
                               == 'North York'].reset_index(drop=True)
northyork_data.head()

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
3,M3B,North York,Don Mills North,43.745906,-79.352188
4,M6B,North York,Glencairn,43.709577,-79.445073

In [108]:
address = 'North York, Toronto'
geolocator = Nominatim(user_agent="Toronto_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinates of North York are {}, {}.'.format(
    latitude, longitude))

The geograpical coordinates of North York are 43.7543263, -79.44911696639593.

<h3>Create map of North York using latitude and longitude values</h3>

In [109]:
map_NorthYork = folium.Map(location=[latitude, longitude], zoom_start=10)
for lat, lng, label in zip(northyork_data['Latitude'], northyork_data['Longitude'], northyork_data['Neighborhood']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_NorthYork)
map_NorthYork

<h3>Foursquare Credentials and Version</h3>

In [112]:
CLIENT_ID = 'P2MGPUXJG1RUBIVCB2OUICQTJ5WFL0QFN0EGDKE20ESPN1O2'
CLIENT_SECRET = 'WCHHX33L0PD5QQERPYEUURZIITH4MAQE3ZXRS4O5AAWM3YSA'
VERSION = '20180604'
LIMIT = 100

<h3>Top 50 venues within a 300 meter radius of chosen Neighborhood</h3>

In [113]:
northyork_data.loc[0, 'Neighborhood']

'Parkwoods'

Find co-ordinates of Parkwoods

In [114]:
neighborhood_latitude = northyork_data.loc[0, 'Latitude']
neighborhood_longitude = northyork_data.loc[0, 'Longitude']
neighborhood_name = northyork_data.loc[0, 'Neighborhood']  # neighborhood name
print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name,
                                                               neighborhood_latitude,
                                                               neighborhood_longitude))

Latitude and longitude values of Parkwoods are 43.7532586, -79.3296565.

<h3>Top 50 Venues within 1000 meters</h3>

In [116]:
LIMIT = 50
radius = 1000
ACCESS_TOKEN = 'MH3GX20WHR1YYNVGXTNCHXHO2SZFQ3UOFKP5SQ3WMHNR1AIF'
VERSION = '20180604'
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID,
    CLIENT_SECRET,
    VERSION,
    neighborhood_latitude,
    neighborhood_longitude,
    radius,
    LIMIT)
results = requests.get(url).json()
items = results['response']['groups'][0]['items']
items[0]

{'reasons': {'count': 0,
  'items': [{'summary': 'This spot is popular',
    'type': 'general',
    'reasonName': 'globalInteractionReason'}]},
 'venue': {'id': '4b8991cbf964a520814232e3',
  'name': "Allwyn's Bakery",
  'location': {'address': '81 Underhill drive',
   'lat': 43.75984035203157,
   'lng': -79.32471879917513,
   'labeledLatLngs': [{'label': 'display',
     'lat': 43.75984035203157,
     'lng': -79.32471879917513}],
   'distance': 833,
   'postalCode': 'M3A 1Z5',
   'cc': 'CA',
   'neighborhood': 'Parkwoods - Donalda',
   'city': 'Toronto',
   'state': 'ON',
   'country': 'Canada',
   'formattedAddress': ['81 Underhill drive', 'Toronto ON M3A 1Z5', 'Canada']},
  'categories': [{'id': '4bf58dd8d48988d144941735',
    'name': 'Caribbean Restaurant',
    'pluralName': 'Caribbean Restaurants',
    'shortName': 'Caribbean',
    'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/caribbean_',
     'suffix': '.png'},
    'primary': True}],
  'photos': {'count': 0, 'groups': []}},
 'referralId': 'e-0-4b8991cbf964a520814232e3-0'}

In [117]:
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']

    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

clean the json and structure it into a pandas dataframe

In [118]:
venues = results['response']['groups'][0]['items']
nearby_venues = json_normalize(venues)
filtered_columns = ['venue.name', 'venue.categories',
                    'venue.location.lat', 'venue.location.lng']
nearby_venues = nearby_venues.loc[:, filtered_columns]
nearby_venues['venue.categories'] = nearby_venues.apply(
    get_category_type, axis=1)
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]
nearby_venues.head(10)

/var/folders/3b/lgj4tzx107q7s73csxsnf0x80000gn/T/ipykernel_76741/4221471.py:2: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  nearby_venues = json_normalize(venues)

                       name            categories        lat        lng
0           Allwyn's Bakery  Caribbean Restaurant  43.759840 -79.324719
1           Brookbanks Park                  Park  43.751976 -79.332140
2               Tim Hortons                  Café  43.760668 -79.326368
3         Bruno's valu-mart         Grocery Store  43.746143 -79.324630
4                       A&W  Fast Food Restaurant  43.760643 -79.326865
5               Food Basics           Supermarket  43.760549 -79.326045
6  High Street Fish & Chips     Fish & Chips Shop  43.745260 -79.324949
7        Shoppers Drug Mart              Pharmacy  43.745315 -79.325800
8        Shoppers Drug Mart              Pharmacy  43.760857 -79.324961
9               Pizza Pizza           Pizza Place  43.760231 -79.325666